### ISSUE TITLE
Original setup is not working

### ISSUE THREAD

**Issue by liukiti** [deploythefleet/arduino_ble_provisioning#1]
Basically related to libpython2.7 and virtualenv issues.

**Comment by sidwarkd** [comment]
@liukiti I'm so sorry I never responded to this. I don't recall getting a notification from Github on it. In any case, glad you got it figured out.  You can also change the base image to debian:bullseye-slim although I like your approach as it allows you to be on stable-slim. I'll play around with this some more and update the repo accordingly.

**Comment by sidwarkd** [comment]
Turns out we can drop the Python 2.7 dependency. That was an artifact I brought over from another devcontainer setup. This way we don't have to add the bullseye sources which creates a [FrankenDebian](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian). Will push a change for this shortly.
